springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    disable-swagger-default-url: true
    filter: true
    path: /swagger-docs
    tryItOutEnabled: true
app:
  version: ^project.version^
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    active: local
