spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demo_db?currentSchema=public
    username: demo_user
    password: demo_password
  jpa:
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5433/demo_db?currentSchema=public
    user: demo_user
    password: demo_password
